project: 
  type: website
  output-dir: docs

website:
  title: "Dylan Turk - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/dtturk01/Data-Science-Portfolio
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Dylan 2026©"
    right: 
      - icon: linkedin
        href: Your_LinkedIn_URL

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Housing Telework Data"
        file: Housing-Telework.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Housing Telework"
      style: "docked"
      background: light
      contents:
        - text: "Housing Telework Data"
          file: Housing-Telework.qmd
  

  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



